namespace Sotn;

public enum Relic
{
    SoulOfBat = 0,
    FireOfBat = 1,
    EchoOfBat = 2,
    ForceOfEcho = 3,
    SoulOfWolf = 4,
    PowerOfWolf = 5,
    SkillOfWolf = 6,
    FormOfMist = 7,
    PowerOfMist = 8,
    GasCloud = 9,
    CubeOfZoe = 10,
    SpiritOrb = 11,
    GravityBoots = 12,
    LeapStone = 13,
    HolySymbol = 14,
    FaerieScroll = 15,
    JewelOfOpen = 16,
    MermanStatue = 17,
    BatCard = 18,
    GhostCard = 19,
    FaerieCard = 20,
    DemonCard = 21,
    SwordCard = 22,
    Jp0 = 23,
    Jp1 = 24,
    HeartOfVlad = 25,
    ToothOfVlad = 26,
    RibOfVlad = 27,
    RingOfVlad = 28,
    EyeOfVlad = 29,
}
